### ISSUE TITLE
How to make a login check

### ISSUE THREAD

**Issue by BalloonInd** [trevorsenior/snoocore#106]
I want to make a login check to see if a given user is logged in.

This code here:

var reddit = new Snoocore({
    userAgent: 'logonTest',
    login: { username: 'yourUsername', password: 'yourPassword' }
});

var loginPromise = reddit.login();

Gives me an object - how do I determine from this whether the user actually successfully logged in?

**Comment by trevorsenior** [comment]
If you're using cookie based login, I think the endpoint *was* `/api/me.json` which will tell you who you've logged in as.

However you will need make the switch to script based OAuth eventually as that will no longer be supproted soon. It isn't so bad to setup: 

http://tsenior.com/snoocore/oauth-script.html

Once authenticated, you can use the endpoint:

https://www.reddit.com/dev/api#GET_api_v1_me

to make sure you've authenticated.

- - -

Responses on my part will be slow as I'm on vacation, but feel free to ask away and I'll eventually get back with you (or someone else may help out).

**Comment by BalloonInd** [comment]
My main issue was it redirected my app to a different URL to authenticate, and after authentication it wanted to send me to another URL - and I was doing it from a mobile app, so that didn't work.

**Comment by trevorsenior** [comment]
Ah, I am not familiar with how Phonegap operates. Unfortunately this involves too much time to look into while on vacation; however, here is some information that may be of use.

- - -

## The push for OAuth

I still say it's worth tinkering with and figuring out how to integrate OAuth with Phonegap.

You won't want to use script based OAuth and instead use [explicit OAuth](http://tsenior.com/snoocore/oauth-explicit.html) (but it seems like you've figured out already). Your app will be `installed` because it will *not* contain a secret (unless you're running a web server) and will run on users phones.

I can't vet for the quality of [this article](http://www.minemobile.com/google-api-oauth-with-phonegaps-inappbrowser/), but it seems that OAuth is possible to setup using an **InAppBrowser** with Phonegap. I haven't read through it, but it seems possible to do at least.

- - -

## Cookie Login (username / password)

Back to the original question, here is some more documentation on the deprecated `GET /api/me.json` call

https://web.archive.org/web/20131123145954/http://www.reddit.com/dev/api#POST_api_login

This is a *working* (as of 2.7.2) version of some code that runs in node.js version 0.10.32 (give it a go yourself!):

```javascript
var Snoocore = require('Snoocore'); // 2.7.2

var reddit = new Snoocore({
  userAgent: 'loginTest',
  login: {
    username: 'test1232eee',
    password: '11111111'
  }
});

reddit.login().then(function() {
  return reddit('/api/me.json').get()
}).then(function(result) {
  console.log(result);
});
```

**Comment by BalloonInd** [comment]
Yep, the login stuff all worked.
