### ISSUE TITLE
POST /api/site_admin doesn't seem to work

### ISSUE THREAD

**Issue by tamadra** [trevorsenior/snoocore#77]
I'm trying to use snoocore to update the sidebar text (aka, "description") in my subreddit. However, I can't seem to get it to work.

The API in question: https://www.reddit.com/dev/api#POST_api_site_admin

My code, roughly:

```javascript
// fetch the edit.json for my-subreddit
reddit.login().then(reddit('/r/my-subreddit/about/edit.json').get().then(function(result){

  // change the description of my-subreddit slightly
  result.data.description += "some text appended at the end";

  // now submit the json object back to reddit
  reddit.login().then(reddit('/api/site_admin').post(result).done()).done();

})).done();
```

Any help? Thanks.

**Comment by trevorsenior** [comment]
Sadly it's a wart in the Reddit API. In short, you need to add some extra options to the POST `/api/site_admin`. 

The following code works:

```javascript
var Snoocore = require('snoocore'); // version 2.1.0

var reddit = new Snoocore({
  userAgent: 'subreddit about.json test',
  login: {
    username: '****',
    password: '****'
  }
});


reddit.login().then(function() {
  return reddit('/r/snoocore/about/edit.json').get();
}).then(function(result) {

  var data = result.data;

  // MUST specify these extra options.
  // unfortunately /about/edit.json does not provide all the
  // parameters for the /api/site_admin call

  data.api_type = 'json'; // must be the sttring 'json'

  // NEEDED ALIASES
  data.sr = data.subreddit_id; // add .sr alias for subreddit_id
  data.link_type = data.content_options // add .link_type alias for content_options
  data.type = data.subreddit_type // add .type alias for subreddit_type

  // Finally, make any actual changes needed
  data.description += ' it works!';

  console.log(data);

  return reddit('/api/site_admin').post(data);

}).done(function(result) {
  console.log(JSON.stringify(result, null, 4));
});
```

Let me know how this works for you.

**Comment by tamadra** [comment]
Thanks! Sounds good. 

BTW, was this described somewhere in the documentation? I looked around before opening this issue and might've missed it. If not, it might be helpful for future users.

**Comment by trevorsenior** [comment]
Reddit’s documentation has everything there, but it isn’t always clear that you **need** `api_type: 'json'`. 

I've kind of covered this in the documentation under "gotcha's" **but** it requires some inspecting of results which most users would not consider doing (e.g. checking the results of `/api/site_admin`).

I've hesitated auto-filling in `api_type` for api calls to keep the library as "pure" / close to the raw API as possible, but I may bend this rule for `api_type` and default it to the string "json" due to the number of issues that it causes users when it *isn't* there.

Besides the whole missing `api_type` issue, there was another one as well.

When you opened this question you actually discovered a new Reddit error I haven't come across! Check out issue #78 for more information. Basically once implemented it will reject the promise when reddit returns errors in this case.

It would have been clear that the parameters in the result for `/about/edit.json` were in fact not what `/api/site_admin` wanted... or at least a little more clear :wink:

**Comment by trevorsenior** [comment]
Oh, I should also mention that you only need to call `login()` once vs. how you did it in the first example. I'll refine the documentation on that tomorrow.

**Comment by tamadra** [comment]
Yup, makes sense. I did notice that the result.json.errors property had some helpful error messages during my debugging. I figured out that reddit was expecting properties in the POST call that it had not supplied in the GET, but I would've never figured out all the aliasing that you showed above.

Unrelated to this issue, does snoocore do any encode/decode html-entities for the data that reddit passes back? For example, if your subreddit description has a > sign, it will be encoded as &gt; in the returned JSON, but if you POST that back to reddit, your subreddit description will now show "&gt;" instead of ">" in the sidebar. I currently using a 3rd party library to decode all html-entities, but it'd be nice if snoocore had an option to handle this transparently for the user.

I've used a library called PRAW for python scripts that use the reddit API and they have this configuration.

See:
https://github.com/praw-dev/praw/issues/186
http://praw.readthedocs.org/en/latest/pages/configuration_files.html?highlight=decode_html_entities

**Comment by trevorsenior** [comment]
It would have to be a configuration option similar to PRAW, with the default being disabled.

It *is* possible to blindly decode the entire reddit response before parsing the JSON response. This is how PRAW handles the situation. https://github.com/praw-dev/praw/blob/v2.1.19/praw/__init__.py#L387

- - -

As of now, Snoocore is very high level & does not dive into *specific* endpoints and never will - someone can write a wrapper for Snoocore for this type of functionality. The only exception is authentication and listing support because that can be hard to handle correctly. However even listing support is high level because it works for all listings, and is not specific to any one listing.

For listings, my other project [trevorsenior/snooform](https://github.com/trevorsenior/snooform) parses the reddit api determines if an endpoint is a listing and adds [an attribute](https://github.com/trevorsenior/snooform/blob/0.1.1/build.js#L215) `isListing`. Snoocore uses the output from the generated api so it knows which endpoints are listings without any performance hits.

This works because in the documentation Reddit clearly defines what a listing is so I can search for the attributes (`'before', 'after', 'limit', 'count', 'show'`) in an endpoint, and if they exist mark it as a listing! Sadly this is not the case for `/about/edit.json` - there is no way to determine what needs to be decoded.

- - -

I think blindly decoding every response it a bit much (how PRAW goes about it) and would prefer something more specific.

If it were to be supported globally (PRAW-like), the configuration would gain an extra value:

```javascript
var reddit = new Snooroce({
  userAgent: 'test',
  oauth: { /* ... */ },
  decodeHtmlEntities: true // default false
});
```

Another way to handle this is expanding the *per call* options. Currently there is only one, [`bypassAuth`](https://github.com/trevorsenior/snoocore/blob/2.1.0/Snoocore.js#L193) ([docs]**(http://tsenior.com/snoocore/advancedUsage.html)) that allows you to skip authentication for a single call, but it can support `decodeHtmlEntities`:

```javascript
reddit('/about/edit.json').get({created: true}, {decodeHtmlEntities: true}).then(/* */)
```

By handling it on a per call basis, we don't have any performance hits of decoding every call blindly even if there is nothing to decode.

Thoughts?

<sub>** probably going to move the `bypassAuth` documentation into a "per call" configuration page if `decodeHtmlEntities` is added in. Making this note in case link provided breaks at a later date.</sub>

**Comment by tamadra** [comment]
Yeah, I see your dilemma. I do think a lot of libraries struggle with this same decision somewhere in their development.
IMO, it's perfectly justified for a wrapper library to stay as thin as possible and "pass along" the warts of the underlying interface, but it's also a sign of a well-designed wrapper if it can help plug any leaky abstractions or alleviate common pitfalls of working with the underlying technology.

Here, Reddit has made the (unfortunate) decision to leave these fields un-decoded for security reasons, not for usability one. I have to imagine that due to the inappropriateness of having html-encoded entities in non-html domains, almost all users of these calls have to do the same post-processing.

Personally I'm not opposed to the global-level configuration. I think the performance hit of over-decoding is probably negligible compared to the overhead of the HTTP calls that are being performed for each call. Or maybe your code can maintain a private list of the calls/fields that you know need to be decoded.

Your call!

**Comment by trevorsenior** [comment]
I'll support both methods and won't cause too much harm or bloat. (I'm thinking of that strange case where you want it decoded 99% of the time, and you want one call that *isn't* decoded).

I'm working on #75 at the moment, then I'll jump over to #79. I'll push both of these issues in version `2.2.0` and will ping you in issue #79 when it's complete. Thanks for your input!
