### ISSUE TITLE
Throttling is incorrectly affected by slow responses

### ISSUE THREAD

**Issue by go1dfish** [trevorsenior/snoocore#84]
Reddit's API request rules specify:

Make no more than thirty requests per minute. 

But the current implementation of Snoocores throttling does not seem to allow new requests to initiate while waiting for a response for a long one, even if sufficient time has passed, causing my bot to hang unnecessarily.  A pre-snoocore implementation of my bot was able to initiate additional requests in these situations, but after porting to snoocore it is a minor hindrance.  

Shouldn't the throttling only apply on the front end of the request and disregard how long it takes for it to complete?

I know it's possible to disable the throttling entirely and recreate my own but that ideally shouldn't be necessary.

Also, very nice library, way better than my attempt with Nodewhal, I will be deprecating that project and redirecting users here.

**Comment by trevorsenior** [comment]
Aww this library has its warts here and there. If anyone from Nodewhal has any questions on porting over / etc. I'm always checking GitHub issues. The questions help find holes in the documentation (or potential bugs!) so they're always welcome.

- - -

Now onto the problem-solving process:

Do you have any small-ish code example that I could look at that reproduces the problem? I don't mind taking a look at your current code if it's a public project on GitHub.


> Shouldn't the throttling only apply on the front end of the request and disregard how long it takes for it to complete?

This is how it [currently works](https://github.com/trevorsenior/snoocore/blob/2.4.0/Snoocore.js#L262). 

To test this further, I went in and manually made every request take 10 seconds (as if every call to reddit took 10+ seconds). I modified [this section of code](https://github.com/trevorsenior/snoocore/blob/2.4.0/Snoocore.js#L308) to look like this:

```javascript
return delay(10000).then(function() {
   return Snoocore.request.https({
     method: method,
     hostname: parsedUrl.hostname,
     path: parsedUrl.path,
     headers: headers
   }, args);
}).then(function(response) {
```

and ran the following code:

```javascript
var Snoocore = require('./Snoocore');

var reddit = new Snoocore({userAgent: 'test'});

reddit('/hot').get().done(function() { console.log(1); });
reddit('/hot').get().done(function() { console.log(2); });
reddit('/hot').get().done(function() { console.log(3); });
reddit('/hot').get().done(function() { console.log(4); });
reddit('/hot').get().done(function() { console.log(5); });
reddit('/hot').get().done(function() { console.log(6); });
```

What the above code does is wait 10 seconds, print `1`, wait 2 seconds, print `2`, wait 2 seconds, print `3`, and so on. Even though every call took 10 seconds, it started the next one after the throttle timer was up. The above code takes ~20 seconds to run.

When the code is structured like this:

```javascript
reddit('/hot').get().then(function() {
  console.log(1);
  return reddit('/hot').get();
}).then(function() {
  console.log(2);
  return reddit('/hot').get();
}).then(function() {
  console.log(3);
  return reddit('/hot').get();
}).then(function() {
  console.log(4);
  return reddit('/hot').get();
});
```

It will wait 10 seconds between each `console.log` because the promise from `reddit('/hot')` will not resolve until we get back information from reddit . The above code takes ~40 seconds to run, while the first example takes ~20 seconds to run even though it makes more calls.

If you're code expects "burst" calls (e.g. 30 calls in 1 second per minute) that isn't *currently* supported but can be if there is enough demand for it.

All in all I'll need so see some code or at least a description (with endpoints) of what you're trying to do.

**Comment by go1dfish** [comment]
Ah ok, I don't know if Nodewhal had many users outside of me (there were a couple though) and it's main design goal was reddit with promises.

But you seem to have nailed that much better than me, I did just enough to get my bot working at the time and went from there.  But you've taken the time to really focus on making a highly reusable library.

I tried to look through the throttling code and didn't follow what it was trying to do immediately, but it sounds like you've got it implemented pretty much how I do.  What I probably experienced was just reddit hanging so bad that all of my outstanding requests were hanging at once.

My bot uses promises as a kind of cooperative multi tasking system with multiple 'threads' of repeating promise chains.

So it's not a simple example but it's here: 
https://github.com/go1dfish/politic-bot

One of the main reasons I like this project is because unlike me you've really focused on testability.

I was too lazy for that with Nodewhal.
